services:
  pocketbase:
    build: ./pocketbase
    container_name: pocketbase
    ports:
      - "8080:8080"
    volumes:
      - ./pb_data:/pb/pb_data
    restart: unless-stopped
    networks:
      - kds-network

  backend:
    build: ./backend
    container_name: express-api
    ports:
      - "3001:3001"
    depends_on:
      - pocketbase
    restart: on-failure
    networks:
      - kds-network

  frontend:
    build: ./frontend
    container_name: react-app
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - pocketbase
    restart: on-failure
    networks:
      - kds-network

networks:
  kds-network:
    driver: bridge